name: Release

on:
  push:
    branches: [ "main" ]

jobs:

  generate-version:
    name: Bump version and release
    runs-on: ubuntu-latest
    outputs:
      current-version: ${{ steps.release-version.outputs.current-version }}
      next-version: ${{ steps.release-version.outputs.next-version }}
    steps:
      - name: Release version
        id: release-version
        uses: tomtom-international/commisery-action/bump@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          create-release: true

  publish-package:
    name: Publish package
    needs: generate-version
    secrets: inherit
    if: needs.generate-version.outputs.next-version != ''
    uses: ./.github/workflows/release_build.yml
    with:
      package-version: ${{ needs.generate-version.outputs.next-version }}
      publish: true
